name: easy_localization_loader
description: Easy Localization Loader custom assets loaders for easy_localization (Json, CSV, http, Xml, API ...)
# author: AISSAT abdelwahab <mr.aissat@gmail.com>
homepage: https://github.com/aissat/easy_localization_loader
issue_tracker: https://github.com/aissat/easy_localization_loader/issues

version: 2.0.3

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^7.0.0
  csv: ^6.0.0
  easy_localization: ^3.0.8
  http: ^1.6.0
  path_provider: ^2.1.5
  xml: ^6.6.1
  yaml: ^3.1.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.27.0